### ISSUE TITLE
Should we remove historical data from nflgame?

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#22]
Just spitballing.  Serious implications with this idea, but what if we leave the historic data / records / searching PURELY to nfldb.

This project becomes more focused on what its good at, digging out data from NFL's shitty api's.

This allows us to;

1. Separate some concerns between nflgame and nfldb.  Currently nflgame and nfldb have overlap.  This is confusing to end users unfamiliar with these projects and... more importantly... is duplicated work.
2. Make nflgame teeny tiny

**Comment by derek-adair** [comment]
@ochawkeye  is probably the best authority on how much overlap there is, and perhaps the amount of work that this would entail.

**Comment by ochawkeye** [comment]
I would absolutely hate that.  

`nfldb` is great!  It's very powerful and allows for much faster queries over complex data sets than what `nflgame` is capable of.

But while I use it on occasion, the bulk of my scripts (and all of my live scoring stuff) is run using `nflgame` exclusively.

**Comment by derek-adair** [comment]
May I ask why?

The quick data access stuff is just better? is the api more friendly?  I've not implemented nfldb yet, but intend to replace my HAPHAZARD attempt at a db with it.

**Comment by derek-adair** [comment]
> I would absolutely hate that

Is this coming from a design perspective or the dread of updating legacy code?

**Comment by derek-adair** [comment]
Would your live scripts be affected if we maintained the same functionality, but did not include historic data?

Personally I dont get why its included at all in the pypi listing.  I think it would be nice to not have a 45MB download, and we could easily release the data as some kind of pypi fixture thingy `nflgame-data` which would satisfy my complaint that the pypi listing is HUUUGE.

  Additionally, this will become more problematic as time goes on.

**Comment by ochawkeye** [comment]
The vast majority of what I'm using `nfl*` for is for the data that is being updated constantly while games are running.  There's just not as compelling of a reason to use a database for that stuff that is constantly being replaced.

One of the nice things about `nflgame` is that, because it has knowledge of that historical data, if you ask it to retrieve data for a game that is completed, it first checks to make sure that completed .json doesn't already exist.  There's no reason to pull the data from NFL.com every single time you want to know something about a game that happened in 2009.  But in order to determine if we actually need to download the data from NFL.com with no historical context we need to check another (non-dependent) library's database?  That seems incredibly convoluted.

Removing the historical data from the release wouldn't affect me a bit...because I already have the historical data.  But the impact on a new user would be massive.  In my opinion, this would be one of the fastest ways to draw the ire of the NFL.

Try running the following (you might have to first delete 2016121103.json 2012121612.json, 2009110900.json, and 2015101108.json from \gamecenter-json - those appear to be corrupt in what you have posted to PyPi or they corrupted when installing on my end only during `pip install`)

```python
import nflgame
import time

start = time.time()
games = nflgame.games(range(2009, 2018), kind='REG')
print len(games)
print time.time()-start
```

When those are on disk it still takes my ancient system 83 seconds to collect all the game data.  I can't even imagine how long it would take if, instead of pulling from disk it was downloading each and every one of the 2304 games from NFL.com.  Not to mention that every single user of `nflgame` will now be hitting NFL.com an extra 2304 times to download the data instead of just the one time it took to do it to build the distribution.

So you can give every user the data at time of install for the cost of 45MB - a task that takes, what, 30 seconds at (zzzzz) 10Mb/s.  Or, you can tell them to get the data themselves - a task that will take potentially hours to do only after a couple thousand calls to NFL.com.  Multiply that by 10 users...100 users...1000 users(?).  Sounds like a cease and desist from the NFL waiting to happen.

**Comment by mickeelm** [comment]
As long as `nflgame` has its own datasource, "hosted" within the `nflgame` repo/directory structure, e.g. the json files, then I think we should keep the historical data in the package too. 45MB isn't much although I can understand the satisfaction, the _feeling_ of having a smaller `nflgame`-package in PyPi. Feels cleaner. But if we're still running this in a couple of years and the files are, say, 70MB, the speed of the internet connections for most people will have increased also so I don't think that it's gonna be a problem. It's still a very small operation.

> Separate some concerns between nflgame and nfldb. Currently nflgame and nfldb have overlap. This is confusing to end users unfamiliar with these projects and... more importantly... is duplicated work.

Haven't looked into `nfldb`, but what kind of overlap is there? Like, do you mean that the data is in both json-files and the PostgresDB? I don't know but I think there is no data included in `nfldb`, you are supposed to get it from `nflgame`, right? Don't know if I understood this correct, e.g. where is the duplicated work? So

> Serious implications with this idea, but what if we leave the historic data / records / searching PURELY to nfldb.

doesn't really make sense to me if you get the db data from `nflgame`. It would result in `nflgame` downloading it all again anyway, wouldn't it?

Well you guys know by know that I like the separation of concerns thing so I'm with you there, but I don't see how removing historical data from PyPi helps this. Please enlighten me, probably don't get the whole picture here :smile:

**Comment by mickeelm** [comment]
Right, after a good night's sleep...

@derek-adair, if you mean by this 

> Just spitballing. Serious implications with this idea, but what if we leave the historic data / records / searching PURELY to nfldb.

That _all_ data (not only historical) should be handled by `nfldb`, or you know _a database_ but not .json-files, this is the direction I'm leaning towards in my own application. Pretty much merging `nflgame` and `nfldb` into one, at least the main ideas of them. Simply because I think that it is a better solution to let a db handle the data for a lot of reasons, and it fits my use case much better. Many users of `nflgame` will disagree.

So taking that step in _this_ fork I'd say would be a statement saying that we're not really developing `nflgame` further here, rather picking the goods from Andrew's different projects into a new one. Big changes, at least. Would be trickier for a lot of users to just go from the old `nflgame` to `nflgame-redux` with this change. So I think that it is up to you, what kind of fork you want. I think it's important for you to feel motivated in maintaining a product that you feel goes in the right direction, otherwise you'll probably want to abandon it sooner rather than later.

Regardless of solution, the only alternative that I can think of, that still would protect us from NFL.com overload but with the added benefit (?) of not providing historical data with the package, is a programmatical barrier that says "hey, you don't have any historical data, would you like to get it? run get_historical_data.py" or "install nflgame-data" (like you suggested) or something like that, and that script simply downloads the historical data from this repo, a PyPi-package, whatever, but not NFL.com which would be blocked.

**Comment by derek-adair** [comment]
> I think there is no data included in nfldb, you are supposed to get it from nflgame, right?

I'm unsure if nfldb has the data migrations built in, but it likely doesnt.  I am just sayin gthat a postgres DB of this would be smaller and faster to query.

There is a way to reorganize these projects in a way that a) does not increase query to NFL.com and b) does NOT break any existing implementation in any meaningful way.

**Comment by derek-adair** [comment]
RE: @ochawkeye 
>The vast majority of what I'm using nfl* for is for the data that is being updated constantly while games are running. 

My guess as to why MOST people, including myself use this project and WHY it seems like a good opportunity for improvement by shifting some of this stuff around.  It's even possible to *REDUCE* queries and dependencies on nfl.com. 

I have some thinking and planning to do that I really do not have much time at the moment.
