### ISSUE TITLE
Feature reuqest: # of plays ran by offense and defense

### ISSUE THREAD

**Issue by naymikm** [derek-adair/nflgame#53]
Number of Offensive and Defensive plays would be a nice feature

**Comment by derek-adair** [comment]
You can pretty easily get this info on your own.  For now, dont expect much on these types of requests.  Eventually, these types of convienence methods would be very nice to have indeed!

**Comment by tabalint** [comment]
Decided to take a look at this. This query gets total plays run by each team for every game. This includes kickoffs and plays re-run because of penalties, and also timeouts and quarter ends (those are filed under Unknown Team)

```
import nfldb
from itertools import groupby

db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2015).game(season_type='Regular')
game_list = [(x.gsis_id, x.pos_team, x.play_id, x.description) for x in q.as_plays()]
game_dict = {k: {k1: sum(1 for _ in v1)
                 for k1, v1 in groupby(sorted(list(v)), lambda x: x[1])}
             for k, v in groupby(game_list, lambda x: x[0])}

print(game_dict)
```

`{'2015112903': {'UNK': 12, 'HOU': 87, 'NO': 71}, '2015112902': {'STL': 84, 'UNK': 13, 'CIN': 74}, '2015112901': {'ATL': 72, 'UNK': 13, 'MIN': 83}, ...`

You could probably get clever and erase plays that didn't happen and kickoffs, but this is a starting point.
