### ISSUE TITLE
PG_Config Executable not found

### ISSUE THREAD

**Issue by ssheikh210** [derek-adair/nflgame#56]
Hi All,

I've taken upon the task of setting up this database and using it for my fantasy league. I have zero experience programming, not familiar with python, but thought it would be fun to learn.

I followed [this guide](https://github.com/BurntSushi/nfldb/wiki/Detailed-Windows-PostgreSQL-installation) and have gotten to pretty much the final steps. The issue I'm having however, is that when I try to install nfldb, it spits back an error at the end of the install: 

Error: pg_config executable not found.

pg_config is required to build psycopg2 from source.  Please add the directory

containing pg_config to the $PATH or specify the full executable path with the

option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

If you prefer to avoid building psycopg2 from source, please install the PyPI

'psycopg2-binary' package instead.

For further information please check the 'doc/src/install.rst' file (also at

<http://initd.org/psycopg/docs/install.html>).

I have no idea what that means at all. I've tried googling the subject, and I can't seem to grasp exactly what is going on here.

I've also attached the piplog so you can see the log for yourself.

Any advice for a newbie?

Thanks everyone
[pip.log](https://github.com/derek-adair/nflgame/files/2757747/pip.log)

**Comment by ochawkeye** [comment]
Try wrapping that entire path --pg_config path in quotation marks.  It's probable that it thinks you're passing it a non-existent path `C:\Program`

**Comment by ochawkeye** [comment]
For Windows, I just install from these pre-compiled versions.

https://www.lfd.uci.edu/~gohlke/pythonlibs/#psycopg

Download the .whl file and `pip install C:\path\to\the\downloaded\file.whl`

**Comment by derek-adair** [comment]
Try installing the windows port of pyscopg, which is recommended by [pyscopg](http://initd.org/psycopg/docs/install.html#install-from-a-package)
-------------------------
Closing because this is not an nflgame issue, and probably not even nfldb issue... and i'm super OCD.  I'll continue to provide any support I can, i just... have this thing about non-relevant issues.

 If anyone is able to confirm the [linked guide](https://github.com/BurntSushi/nfldb/wiki/Detailed-Windows-PostgreSQL-installation) still works that'd be great!

**Comment by ochawkeye** [comment]
Those are the same steps I just followed in November when I built up an install on a new PC.
