### ISSUE TITLE
nflgame: final scores

### ISSUE THREAD

**Issue by scockster** [derek-adair/nflgame#60]
I've tried a mix of things but I'm just not understanding which commands to use together.  I just want a list of scores for each week.  For example, for week 10 of 2018.  I've been using a mixture of these but not necessary in this order.  

import nflgame

games = nflgame.games(2018, week=10)
def nice_score(self)
def is_final(self)
def game_over(self)
 Can I please get some assistance  please.  I have no experience in programming so I'm sorry for so green.  I just need something simple.  Like....
DEN (45) vs. KC (35)

**Comment by mickeelm** [comment]
No need to apologize :) Since you're new to programming, there's some things you need to know. The first thing is that nflgame only runs on Python 2, so if you only have Python 3 installed, it's not gonna work.

You normally use nflgame (use Python, really) in one of two ways. Either you just start a Python interpreter or you execute a script from file. On my system, Python 3 is default so I have to explicitly say python2 when I run it. If you want to do this in an interpreter, you can do like this, I've added some comments as well (please note that this is directly from my system, might look different on yours...):

```
[nflgame]$ python2
Python 2.7.16 (default, Mar 11 2019, 18:59:25) 
[GCC 8.2.1 20181127] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nflgame
>>> games = nflgame.games(2018,10)
>>> for game in games:
...   print(game)  # Note the spaces before print, they're important
...                # Just press enter here
CAR (21) at PIT (52)
DET (22) at CHI (34)
NO (51) at CIN (14)
ATL (16) at CLE (28)
MIA (12) at GB (31)
JAX (26) at IND (29)
ARI (14) at KC (26)
BUF (41) at NYJ (10)
WAS (16) at TB (3)
NE (10) at TEN (34)
LAC (20) at OAK (6)
SEA (31) at LA (36)
DAL (27) at PHI (20)
NYG (27) at SF (23)
>>> 
```
(type `exit()` to get out of the interpreter)

If you want to run this as a script from file, simply create a file with this content

```
import nflgame
games = nflgame.games(2018,10)
for game in games:
  print(game)
```

and save it as `whatever.py` and then just run `python whatever.py` from a terminal (in my case it has to be python2 but that may not be the case for you).

**Comment by derek-adair** [comment]
You should probably check out the [api docs](http://nflgame.derekadair.com/).  Just browse through the menu there.  Forutnately @burntsushi has blessed us with some VERY thorough documentation.

Also I'd highly encourage just browsing the source code to check out how this whole module works.  It's very well made.

**Comment by derek-adair** [comment]
I'll let you close this one ;)

**Comment by derek-adair** [comment]
in hindsight, this appears to be a lack of understanding of how to use python... closing.  Any similar questions are probably best asked on stack overflow or the like.
